# Vivado Tcl Script to Build the Project
# Usage: vivado -mode batch -source scripts/build.tcl

# 1. Create Project
create_project -force bram_latency_study ./bram_latency_study -part xc7z015clg485-2
# set_property board_part ALINX:ax7015:part0:1.0 [current_project]

# 2. Add Sources
# Note: Using relative path from where vivado is launched (root of 08 folder)
add_files -norecurse ./rtl/bram_controller.v

update_compile_order -fileset sources_1

# 3. Create Block Design
create_bd_design "design_1"

# 4. Add Zynq Processing System
startgroup
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 processing_system7_0
endgroup

# Apply automation if available, otherwise manual config might be needed. 
# For standard Zynq parts, we often need to run block automation.
# We will try to run it.
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 -config {make_external "FIXED_IO, DDR" apply_board_preset "1" Master "Disable" Slave "Disable" }  [get_bd_cells processing_system7_0]

# 5. Add BRAM Controller Module
# We need to ensure the module is picked up.
create_bd_cell -type module -reference bram_controller bram_controller_0

# 6. Automate Connections (AXI Interconnect)
startgroup
apply_bd_automation -rule xilinx.com:bd_rule:axi4 -config { Clk_master {/processing_system7_0/FCLK_CLK0 (50 MHz)} Clk_slave {/processing_system7_0/FCLK_CLK0 (50 MHz)} Clk_xbar {/processing_system7_0/FCLK_CLK0 (50 MHz)} Master {/processing_system7_0/M_AXI_GP0} Slave {/bram_controller_0/s_axi} ddr_seg {Auto} intc_ip {New AXI Interconnect} master_apm {0}}  [get_bd_intf_pins bram_controller_0/s_axi]
endgroup

# 7. Connect Native Port B (Loopback or Constant for Dummy Read)
# We will connect Port B clock to valid clock
connect_bd_net [get_bd_pins bram_controller_0/bram_clk_b] [get_bd_pins processing_system7_0/FCLK_CLK0]

# Tie Enable High and Address to a constant for simple activity
create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 xlconstant_en
set_property -dict [list CONFIG.CONST_VAL {1}] [get_bd_cells xlconstant_en]
connect_bd_net [get_bd_pins xlconstant_en/dout] [get_bd_pins bram_controller_0/bram_en_b]

create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 xlconstant_addr
set_property -dict [list CONFIG.CONST_WIDTH {10} CONFIG.CONST_VAL {0}] [get_bd_cells xlconstant_addr]
connect_bd_net [get_bd_pins xlconstant_addr/dout] [get_bd_pins bram_controller_0/bram_addr_b]

# 8. Add ILA to Monitor AXI Latency (System ILA)
# Use System ILA for interface monitoring
startgroup
create_bd_cell -type ip -vlnv xilinx.com:ip:system_ila:1.1 system_ila_0
endgroup

# Configure for Interface monitoring
set_property -dict [list CONFIG.C_MON_TYPE {INTERFACE} CONFIG.C_SLOT_0_INTF_TYPE {xilinx.com:interface:aximm_rtl:1.0}] [get_bd_cells system_ila_0]

# Connect Clock and Reset
connect_bd_net [get_bd_pins processing_system7_0/FCLK_CLK0] [get_bd_pins system_ila_0/clk]
# Use the peripheral reset from the processor system reset block if available, 
# or FCLK_RESET0_N if direct (though usually requires processor system reset ip).
# To be robust, let's use the one generated by automation or directly from PS for now (active low).
connect_bd_net [get_bd_pins processing_system7_0/FCLK_RESET0_N] [get_bd_pins system_ila_0/resetn]

# Monitor the BRAM Controller Slave Port
# The s_axi port is already connected to the interconnect.
# We connect the monitor port to the same interface pin.
# Note: System ILA slot usually takes a monitor connection.
connect_bd_intf_net [get_bd_intf_pins bram_controller_0/s_axi] [get_bd_intf_pins system_ila_0/SLOT_0_AXI]
make_wrapper -files [get_files ./bram_latency_study/bram_latency_study.srcs/sources_1/bd/design_1/design_1.bd] -top
add_files -norecurse ./bram_latency_study/bram_latency_study.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v

# 10. Generate Bitstream
launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1

# Check for success
if {[get_property PROGRESS [get_runs impl_1]] != "100%"} {
   error "Implementation failed!"
}

# 11. Export Hardware and Metrics
write_hw_platform -fixed -include_bit -force -file ./design_1_wrapper.xsa

# Open implemented design to generate reports
open_run impl_1

# Generate Reports
report_timing_summary -file ./bram_latency_study/bram_latency_study.runs/impl_1/timing_summary_routed.rpt
report_utilization -file ./bram_latency_study/bram_latency_study.runs/impl_1/utilization_placed.rpt

# Copy Artifacts to Root
set impl_dir "./bram_latency_study/bram_latency_study.runs/impl_1"
file copy -force ${impl_dir}/design_1_wrapper.bit ./design_1_wrapper.bit
file copy -force ${impl_dir}/timing_summary_routed.rpt ./timing_summary.rpt
file copy -force ${impl_dir}/utilization_placed.rpt ./utilization.rpt

puts "------------------------------------------------"
puts "Build Complete."
puts "Bitstream: ./design_1_wrapper.bit"
puts "Reports:   ./timing_summary.rpt, ./utilization.rpt"
puts "------------------------------------------------"
exit
